name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Deploy on pushes to main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Deploy to GitHub Pages
      - name: Deploy HTML site
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Root directory where your HTML file is
          publish_branch: gh-pages
